appName: currencyservice
appReplicas: 1
appImage: gcr.io/google-samples/microservices-demo/currencyservice
appVersion: v0.2.3
containerPort: 7000
servicePort: 7000
containerEnvVars:
- name: PORT
  value: "7000"        

probe:
- periodSeconds: 5
  execCommand: '["/bin/grpc_health_probe", "-addr=:7000"]'

resources:
- requestCpu: 100m
  requestMemory: 64Mi
  limitsCpu: 200m
  limitsMemory: 128Mi