appName: emailservice
appReplicas: 2
appImage: gcr.io/google-samples/microservices-demo/emailservice
appVersion: v0.2.3
containerEnvVars:
- name: PORT
  value: "8080"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"

livenessProbe:
- periodSeconds: 5
  execCommand: '["/bin/grpc_health_probe", "-addr=:8080"]'

readinessProbe:
- periodSeconds: 5
  execCommand: '["/bin/grpc_health_probe", "-addr=:8080"]'

resources:
- requestCpu: 100m
  requestMemory: 64Mi
  limitsCpu: 200m
  limitsMemory: 128Mi