appName: recommendationservice
appReplicas: 1
appImage: gcr.io/google-samples/microservices-demo/recommendationservice
appVersion: v0.2.3
servicePort: 8080
containerEnvVars:
- name: PORT
  value: "8080"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"
- name: DISABLE_DEBUGGER
  value: "1"  

probe:
- periodSeconds: 5
  execCommand: '["/bin/grpc_health_probe", "-addr=:8080"]'

resources:
- requestCpu: 100m
  requestMemory: 220Mi
  limitsCpu: 200m
  limitsMemory: 450Mi