---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-demo-email
  namespace: microservice-demo
spec:
  selector:
    matchLabels:
      app: microservice-demo-email
  template:
    metadata:
      labels:
        app: microservice-demo-email
    spec:
      containers:
      - name: microservice-demo-email
        image: gcr.io/google-samples/microservices-demo/emailservice:v0.2.3
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080" 
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        livenessProbe:
            periodSeconds: 5
            exec: 
                command: ["/bin/grpc_health_probe", "-addr=:8080"]
        readinessProbe:
            periodSeconds: 5
            exec: 
                command: ["/bin/grpc_health_probe", "-addr=:8080"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi       
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
  namespace: microservice-demo
spec:
  type: ClusterIP
  selector:
    app: microservice-demo-email
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-demo-checkout
  namespace: microservice-demo
spec:
  selector:
    matchLabels:
      app: microservice-demo-checkout
  template:
    metadata:
      labels:
        app: microservice-demo-checkout
    spec:
      containers:
      - name: microservice-demo-checkout
        image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.2.3
        ports:
        - containerPort: 5050
        env:
        - name: PORT
          value: "5050"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"
        - name: SHIPPING_SERVICE_ADDR
          value: "shippingservice:50051"
        - name: PAYMENT_SERVICE_ADDR
          value: "paymentservice:50051"
        - name: EMAIL_SERVICE_ADDR
          value: "emailservice:5000"
        - name: CURRENCY_SERVICE_ADDR
          value: "currencyservice:7000"
        - name: CART_SERVICE_ADDR
          value: "cartservice:7070"
        - name: DISABLE_STATS
          value: "1"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"        
        livenessProbe:
            periodSeconds: 5
            exec: 
                command: ["/bin/grpc_health_probe", "-addr=:5050"]
        readinessProbe:
            periodSeconds: 5
            exec: 
                command: ["/bin/grpc_health_probe", "-addr=:5050"]
        resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: microservice-demo
spec:
  type: ClusterIP
  selector:
    app: microservice-demo-checkout
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 5050

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-demo-recommendation
  namespace: microservice-demo
spec:
  selector:
    matchLabels:
      app: microservice-demo-recommendation
  template:
    metadata:
      labels:
        app: microservice-demo-recommendation
    spec:
      containers:
      - name: microservice-demo-recommendation
        image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.2.3
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_DEBUGGER
          value: "1"
        livenessProbe:
            periodSeconds: 5
            exec: 
                command: ["/bin/grpc_health_probe", "-addr=:8080"]
        readinessProbe:
            periodSeconds: 5
            exec: 
                command: ["/bin/grpc_health_probe", "-addr=:8080"]
        resources:
          requests:
            cpu: 100m
            memory: 220Mi
          limits:
            cpu: 200m
            memory: 450Mi
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  namespace: microservice-demo
spec:
  type: ClusterIP
  selector:
    app: microservice-demo-recommendation
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-demo-frontend
  namespace: microservice-demo
spec:
  selector:
    matchLabels:
      app: microservice-demo-frontend
  template:
    metadata:
      labels:
        app: microservice-demo-frontend
    spec:
      containers:
      - name: microservice-demo-frontend
        image: gcr.io/google-samples/microservices-demo/frontend:v0.2.3
        ports:
        - containerPort: 8080
        readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
              - name: "Cookie"
                value: "shop_session-id=x-readiness-probe"
        livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
              - name: "Cookie"
                value: "shop_session-id=x-liveness-probe"
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"
        - name: CURRENCY_SERVICE_ADDR
          value: "currencyservice:7000"
        - name: CART_SERVICE_ADDR
          value: "cartservice:7070"
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "recommendationservice:8080"
        - name: SHIPPING_SERVICE_ADDR
          value: "shippingservice:50051"
        - name: CHECKOUT_SERVICE_ADDR
          value: "checkoutservice:5050"
        - name: AD_SERVICE_ADDR
          value: "adservice:9555"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_TRACING
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: microservice-demo
spec:
  type: ClusterIP
  selector:
    app: microservice-demo-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservice-demo-frontend-ingress
  namespace: microservice-demo
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod    
spec:
  rules:
  - host: microdemo.linode.systechit.dk
    http:
      paths:
      - backend:
          service:
            name: frontend
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - microdemo.linode.systechit.dk
    secretName: microdemo.linode.systechit.dk-tls

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-demo-payment
  namespace: microservice-demo
spec:
  selector:
    matchLabels:
      app: microservice-demo-payment
  template:
    metadata:
      labels:
        app: microservice-demo-payment
    spec:
      containers:
      - name: microservice-demo-payment
        image: gcr.io/google-samples/microservices-demo/paymentservice:v0.2.3
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"        
        livenessProbe:
            periodSeconds: 5
            exec: 
                command: ["/bin/grpc_health_probe", "-addr=:50051"]
        readinessProbe:
            periodSeconds: 5
            exec: 
                command: ["/bin/grpc_health_probe", "-addr=:50051"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  namespace: microservice-demo
spec:
  type: ClusterIP
  selector:
    app: microservice-demo-payment
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-demo-productcatalog
  namespace: microservice-demo
spec:
  selector:
    matchLabels:
      app: microservice-demo-productcatalog
  template:
    metadata:
      labels:
        app: microservice-demo-productcatalog
    spec:
      containers:
      - name: microservice-demo-productcatalog
        image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.2.3
        ports:
        - containerPort: 3550
        env:
        - name: PORT
          value: "3550"
        livenessProbe:
            periodSeconds: 5
            exec: 
                command: ["/bin/grpc_health_probe", "-addr=:3550"]
        readinessProbe:
            periodSeconds: 5
            exec: 
                command: ["/bin/grpc_health_probe", "-addr=:3550"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: microservice-demo
spec:
  type: ClusterIP
  selector:
    app: microservice-demo-productcatalog
  ports:
  - protocol: TCP
    port: 3550
    targetPort: 3550

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-demo-cart
  namespace: microservice-demo
spec:
  selector:
    matchLabels:
      app: microservice-demo-cart
  template:
    metadata:
      labels:
        app: microservice-demo-cart
    spec:
      containers:
      - name: microservice-demo-cart
        image: gcr.io/google-samples/microservices-demo/cartservice:v0.2.3
        ports:
        - containerPort: 7070
        env:
        - name: REDIS_ADDR
          value: "redis-cart:6379"
        livenessProbe:
            periodSeconds: 5
            exec: 
                command: ["/bin/grpc_health_probe", "-addr=:7070"]
        readinessProbe:
            periodSeconds: 5
            exec: 
                command: ["/bin/grpc_health_probe", "-addr=:7070"]
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: microservice-demo
spec:
  type: ClusterIP
  selector:
    app: microservice-demo-cart
  ports:
  - protocol: TCP
    port: 7070
    targetPort: 7070

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-demo-currency
  namespace: microservice-demo
spec:
  selector:
    matchLabels:
      app: microservice-demo-currency
  template:
    metadata:
      labels:
        app: microservice-demo-currency
    spec:
      containers:
      - name: microservice-demo-currency
        image: gcr.io/google-samples/microservices-demo/currencyservice:v0.2.3
        ports:
        - containerPort: 7000
        env:
        - name: PORT
          value: "7000"
        livenessProbe:
            periodSeconds: 5
            exec: 
                command: ["/bin/grpc_health_probe", "-addr=:7000"]
        readinessProbe:
            periodSeconds: 5
            exec: 
                command: ["/bin/grpc_health_probe", "-addr=:7000"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: microservice-demo
spec:
  type: ClusterIP
  selector:
    app: microservice-demo-currency
  ports:
  - protocol: TCP
    port: 7000
    targetPort: 7000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-demo-shipping
  namespace: microservice-demo
spec:
  selector:
    matchLabels:
      app: microservice-demo-shipping
  template:
    metadata:
      labels:
        app: microservice-demo-shipping
    spec:
      containers:
      - name: microservice-demo-shipping
        image: gcr.io/google-samples/microservices-demo/shippingservice:v0.2.3
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        livenessProbe:
            periodSeconds: 5
            exec: 
                command: ["/bin/grpc_health_probe", "-addr=:50051"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  namespace: microservice-demo
spec:
  type: ClusterIP
  selector:
    app: microservice-demo-shipping
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-demo-redis
  namespace: microservice-demo
spec:
  selector:
    matchLabels:
      app: microservice-demo-redis
  template:
    metadata:
      labels:
        app: microservice-demo-redis
    spec:
      containers:
      - name: microservice-demo-redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 6379
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-data
        resources:
          limits:
            memory: 256Mi
            cpu: 125m
          requests:
            cpu: 70m
            memory: 200Mi        
      volumes:
      - name: redis-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  namespace: microservice-demo
spec:
  type: ClusterIP
  selector:
    app: microservice-demo-redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-demo-ad
  namespace: microservice-demo
spec:
  selector:
    matchLabels:
      app: microservice-demo-ad
  template:
    metadata:
      labels:
        app: microservice-demo-ad
    spec:
      containers:
      - name: microservice-demo-ad
        image: gcr.io/google-samples/microservices-demo/adservice:v0.2.3
        ports:
        - containerPort: 9555
        env:
        - name: PORT
          value: "9555"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_STATS
          value: "1"
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9555"]
        livenessProbe:
            periodSeconds: 5
            exec: 
                command: ["/bin/grpc_health_probe", "-addr=:9555"]             
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: microservice-demo
spec:
  type: ClusterIP
  selector:
    app: microservice-demo-ad
  ports:
  - protocol: TCP
    port: 9555
    targetPort: 9555

